{"name": "test_bubaohan", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 not in [1, 2, 3]", "trace": "def test_bubaohan():\n>       assert 1 not in [1, 2, 3]\nE       assert 1 not in [1, 2, 3]\n\ntest_pytest13.py:38: AssertionError"}, "start": 1711432201039, "stop": 1711432201039, "uuid": "fd2ab1a7-4680-4e6d-bda2-cd2064afd60c", "historyId": "7e36e7f06e0a63af06bb6c199ae84981", "testCaseId": "7e36e7f06e0a63af06bb6c199ae84981", "fullName": "test_pytest13#test_bubaohan", "labels": [{"name": "suite", "value": "test_pytest13"}, {"name": "host", "value": "hackersg"}, {"name": "thread", "value": "23980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest13"}]}